---
exclude: ['README.markdown']
permalink: ':title'
safe: false
title: 'MagicDAQ Docs'

## Jekyll 3 now only supports Kramdown for Markdown
#kramdown:
#    # Use GitHub flavored markdown, including triple backtick fenced code blocks
#    input: GFM
#    # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
#    syntax_highlighter: rouge
#    syntax_highlighter_opts:
#        # Use existing pygments syntax highlighting css
#        css_class: 'highlight'


# Conversion
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  extensions: fenced_code_blocks